name: Release upload
permissions:
  contents: write
on:
  release:
    types:
    - published

jobs:
  package-xgo-build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
    - name: Install Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
      with:
        go-version: 'stable'
    - name: Setup XGO
      run: go install src.techknowlogick.com/xgo@latest
    - name: Run dist
      run: make dist
    - name: Set environment variables
      shell: bash
      run: |
        echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
        echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
    - name: Upload artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
      with:
        name: xgo-build-zip
        path: dist/*.zip

  package-zig-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { GOOS: linux,   GOARCH: amd64, ZIPOS: linux_old, ZIG_TARGET: x86_64-linux-gnu.2.18 }
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
    - name: Install Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
      with:
        go-version: 'stable'
    - name: Setup Zig
      uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29
    - name: make package
      run: |
        export "CC=zig cc -target ${{ matrix.ZIG_TARGET }}"
        make pkg GOOS=${{ matrix.GOOS }} GOARCH=${{ matrix.GOARCH }} ZIPOS=${{ matrix.ZIPOS }}
    - name: Upload artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
      with:
        name: trdsql-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
        path: dist/*.zip

  package-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - { GOOS: darwin, GOARCH: amd64}
          - { GOOS: darwin, GOARCH: arm64}
      fail-fast: false
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
    - name: Install Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
      with:
        go-version: 'stable'
    - name:  make package
      run: make pkg GOOS=${{ matrix.GOOS }} GOARCH=${{ matrix.GOARCH }}
    - name: Upload artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
      with:
        name: trdsql-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
        path: dist/*.zip

  release-upload:
    runs-on: ubuntu-latest
    needs: [package-xgo-build, package-zig-build, package-macos]
    steps:
    -  uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

    - { uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e, with: { name: xgo-build-zip,        path: dist/ } }
    - { uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e, with: { name: trdsql-linux-amd64,   path: dist/ } }
    - { uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e, with: { name: trdsql-darwin-amd64,  path: dist/ } }
    - { uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e, with: { name: trdsql-darwin-arm64,  path: dist/ } }

    - name: Upload Asset to Release with a wildcard
      uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*.zip
